# Generated by Django 5.1.6 on 2025-09-17 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado por farmacia'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('detalles', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_farmacia', to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_repartidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
