# Generated by Django 5.1.6 on 2025-10-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='Direccion por defctoooo', max_length=255),
            preserve_default=False,
        ),
    ]
