# Generated by Django 5.1.6 on 2025-10-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comentario_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_rechazo',
            field=models.CharField(blank=True, choices=[('SIN_STOCK', 'Sin stock'), ('RECETA_INVALIDA', 'Receta inválida'), ('FUERA_DE_COBERTURA', 'Fuera de cobertura'), ('PROBLEMAS_OPERATIVOS', 'Problemas operativos'), ('OTRO', 'Otro')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
