# Generated by Django 5.1.6 on 2025-10-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pedido_direccion'),
        ('orders', '0003_pedido_comentario_rechazo_pedido_motivo_rechazo_and_more'),
    ]

    operations = [
    ]
