# Generated by Django 5.1.6 on 2025-11-03 00:32

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_merge_20251030_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_seguridad',
            field=models.CharField(default=apps.orders.models.generar_codigo_numerico, help_text='Código de seguridad para entrega', max_length=6),
        ),
    ]
