# Generated by Django 5.1.6 on 2025-11-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartidor',
            name='antecedentes',
            field=models.FileField(help_text='Documento de antecedentes (JPG, PNG o PDF).', upload_to='antecedentes_repartidores/'),
        ),
    ]
