# Generated by Django 5.1.6 on 2025-10-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default=22, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.IntegerField(default=22, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='terms_cond',
            field=models.BooleanField(default=False),
        ),
    ]
