# Generated by Django 5.1.6 on 2025-10-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmacia',
            old_name='direccion_farmacia',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='farmacia',
            old_name='nombre_farmacia',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='farmacia',
            name='acepta_tyc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='cbu',
            field=models.CharField(default='000000000000000000000', max_length=22),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='cuit',
            field=models.CharField(default='00-00000000-0', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='documentacion',
            field=models.FileField(null=True, upload_to='documentacion_farmacias/'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='obras_sociales',
            field=models.TextField(blank=True, help_text='Lista separada por comas de las obras sociales que acepta', null=True),
        ),
    ]
