# Generated by Django 5.1.6 on 2025-10-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_direccion_farmacia_farmacia_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='cuit',
            field=models.CharField(default='00-00000000-0', max_length=13, unique=True),
        ),
        migrations.RemoveField(
            model_name='farmacia',
            name='obras_sociales',
        ),
        migrations.AddField(
            model_name='farmacia',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, related_name='farmacias', to='accounts.obrasocial'),
        ),
    ]
