# Generated by Django 5.1.6 on 2025-10-23 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cliente_apellido_cliente_documento_cliente_edad_and_more'),
        ('accounts', '0006_obrasocial_alter_farmacia_cuit_and_more'),
    ]

    operations = [
    ]
